// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmFhPKrVPByybJvJqxW169NtlQr6pbnzw',
    appId: '1:184380367656:web:4187a06a8fe3539e75261d',
    messagingSenderId: '184380367656',
    projectId: 'equinox-empire',
    authDomain: 'equinox-empire.firebaseapp.com',
    storageBucket: 'equinox-empire.appspot.com',
    measurementId: 'G-3L34HEB9YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa64n1YbGtmZkRkR12fHZAo00pYq95i-Q',
    appId: '1:184380367656:android:1c8ed01629ce403275261d',
    messagingSenderId: '184380367656',
    projectId: 'equinox-empire',
    storageBucket: 'equinox-empire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCutaPUWZTymEMEktvQRX2NuAQRMRKIgok',
    appId: '1:184380367656:ios:66803b84a704d91975261d',
    messagingSenderId: '184380367656',
    projectId: 'equinox-empire',
    storageBucket: 'equinox-empire.appspot.com',
    iosBundleId: 'com.example.equinoxempire2',
  );
}
